# this is config_input.py and here all inputs stuff that required to IBScraper to listing jobs from indeed.com

# jobs page urls for listing all jobs first
jobs_listed_pages_urls = [
"https://www.indeed.com/jobs?q=power+bi+analyst&l=United+States&fromage=1&from=searchOnDesktopSerp&vjk=f6fec11c6cb0b807", 
"https://www.indeed.com/jobs?q=data+scientist&l=United+States&fromage=1&from=searchOnDesktopSerp&vjk=921edb4b120e47ac", 
"https://www.indeed.com/jobs?q=analytics%20engineer&l=United%20States&fromage=1&from=searchOnDesktopSerp"

]

# contexts means (google chrome profiles) we will use differents google chrome profiles, proxies and other settings for each context to do fast scraping while doing with one context there are very big chance to block account or indeed server don't giving you reponses to our requests


# In below var we will gave prompt to ai for geting specfic task for now as matching % for each jobs
AI_PROMPT = """
"""

# resume for ai to provide every jobs matching % base one resume
resume = """
I'm AI/ML Engineer
"""

# list of companies to ignore for instance like : apple, amazon, google etc
ignore_companies_jobs = [
"HCA Healthcare", 
"Sumitomo Mitsui Banking Corporation", 
"KeyBank National Association", 
"Infosys", 
"Zoom", 
"Hilton Grand Vacations", 
"Coinbase", 
"Twilio", 
"Gusto", 
"Gainwell Technologies", 
"TEKsystems", 
"Ascensus", 
"ESRI", 
"Northrop Grumman Corporation", 
"Capgemini", 
"DocuSign", 
"Almac Group", 
"Rocket Lab USA", 
"UPS", 
"Marriott International", 
"Cisco Meraki", 
"Walmart", 
"Ltimindtree", 
"Mastercard", 
"Accenture", 
"Equinix", 
"ALTEN Technology", 
"Bloomberg", 
"Apple", 
"Meta", 
"Alphabetic Inc", 
"ExxonMobil", 
"Uber", 
"Federal & Government-Related Organizations:", 
"Association of Universities for Research in Astronomy", 
"SteerBridge Strategies", 
"Bank", 
"Port Technology Services", 
"University", 
"College", 
"KPMG", 
"Blue Origin", 
"IBM", 
"Dell", 
"Hitachi", 
"Sony", 
"Intel", 
"Siemens", 
"TCS", 
"Nestlé", 
"Spotify", 
"Microsoft", 
"Fox Corporation", 
"Liberty Mutual Insurance", 
"Motorola Solutions", 
"Samsung", 
"Mutual of Omaha", 
"Nasdaq", 
"Okta", 
"Visa", 
"Atlassian", 
"Siemens Industry Software Inc.", 
"Toshiba", 
"Panasonic Corporation", 
"Oracle", 
"Thermo Fisher Scientific", 
"Motorola", 
"eBay", 
"GoDaddy", 
"WebMD", 
"Indeed", 
"Gartner", 
"Capital One", 
"Discord", 
"NVIDIA", 
"Amazon.com Services LLC", 
"Amazon Development Center U.S., Inc.", 
"Royal Bank of Canada", 
"Amazon Data Services, Inc.", 
"Google", 
"Amazon Web Services, Inc.", 
"Capgemini Engineering", 
"Amex", 
"Sam's Club", 
"PlayStation Global", 
"NIH-NCBI", 
"United States Senate Sergeant at Arms", 
"floridadep", 
"Lockheed Martin", 
"PricewaterhouseCoopers (PWC)", 
"Khan Academy", 
"American Airlines", 
"Morgan Stanley", 
"BNY Mellon", 
"Nissan", 
"Workday", 
"KLA", 
"Safran", 
"Georgia-Pacific", 
"Mizuho Americas", 
"Twitch", 
"Sallie Mae", 
"Abbott Laboratories", 
"Saab Inc.", 
"McAfee, LLC", 
"United Airlines", 
"Wells Fargo", 
"Fidelity Investments", 
"Northrop Grumman", 
"RTI International", 
"Deloitte", 
"General Dynamics Information Technology", 
"Comcast Corporation", 
"HII", 
"Roblox", 
"Federal Reserve Bank of St. Louis", 
"Blackhawk Network", 
"Blue Cross Blue Shield Association", 
"Textron Aviation", 
"SAIC", 
"Spectrum", 
"Cognizant", 
"Navy Federal Credit Union", 
"Truist Bank", 
"Leidos", 
"Cisco Systems", 
"Collins Aerospace", 
"Teledyne Technologies Inc.", 
"CoStar Group", 
"Trane Technologies", 
"City of Davenport, IA", 
"City of Chesapeake", 
"St Johns River Water Management District", 
"South Dakota Board of Regents", 
"Capital Area Intermediate Unit", 
"University of Maryland", 
"State of Delaware", 
"The State of Florida", 
"Douglas County, CO", 
"The University of Chicago", 
"University of Notre Dame", 
"Maricopa Community Colleges", 
"Qorvo", 
"Tria Federal (Tria)", 
"TSPi", 
"The GBS Group", 
"None explicitly listed", 
"Defense Department", 
"Air Force Department", 
"Army Department", 
"Defense Acquisition Regulations System", 
"Defense Contract Audit Agency", 
"Defense Information Systems Agency", 
"Defense Intelligence Agency", 
"Defense Investigative Service", 
"Defense Logistics Agency", 
"Defense Mapping Agency", 
"Defense Special Weapons Agency", 
"Engineers Corps", 
"National Geospatial-Intelligence Agency", 
"National Security Agency/Central Security Service", 
"Navy Department", 
"Uniformed Services University of the Health Sciences", 
"Defense Nuclear Facilities Safety Board", 
"Education Department", 
"Energy Department", 
"Federal Energy Regulatory Commission", 
"National Nuclear Security Administration", 
"Southeastern Power Administration", 
"Southwestern Power Administration", 
"Western Area Power Administration", 
"Environmental Protection Agency", 
"Equal Employment Opportunity Commission", 
"Executive Office of the President", 
"Federal Communications Commission", 
"Federal Deposit Insurance Corporation", 
"Federal Election Commission", 
"Federal Housing Finance Agency", 
"Federal Maritime Commission", 
"Federal Reserve System", 
"Federal Trade Commission", 
"General Services Administration", 
"Government Accountability Office", 
"Government Ethics Office", 
"Government Publishing Office", 
"Health and Human Services Department", 
"Centers for Disease Control and Prevention", 
"Centers for Medicare & Medicaid Services", 
"Food and Drug Administration", 
"Indian Health Service", 
"National Institutes of Health", 
"Public Health Service", 
"Homeland Security Department", 
"Federal Emergency Management Agency", 
"Transportation Security Administration", 
"U.S. Citizenship and Immigration Services", 
"U.S. Customs and Border Protection", 
"U.S. Immigration and Customs Enforcement", 
"Justice Department", 
"Federal Bureau of Investigation", 
"Drug Enforcement Administration", 
"National Aeronautics and Space Administration", 
"National Archives and Records Administration", 
"National Counterintelligence Center", 
"National Credit Union Administration", 
"National Economic Council", 
"National Security Council", 
"National Transportation Safety Board", 
"Nuclear Regulatory Commission", 
"Occupational Safety and Health Review Commission", 
"Office of National Drug Control Policy", 
"Peace Corps", 
"Pension Benefit Guaranty Corporation", 
"Personnel Management Office", 
"Postal Service", 
"Securities and Exchange Commission", 
"Selective Service System", 
"Small Business Administration", 
"Social Security Administration", 
"Special Counsel Office", 
"State Department", 
"Transportation Department", 
"Federal Aviation Administration", 
"Federal Highway Administration", 
"Federal Motor Carrier Safety Administration", 
"Federal Railroad Administration", 
"Federal Transit Administration", 
"Great Lakes St. Lawrence Seaway Development Corporation", 
"Maritime Administration", 
"National Highway Traffic Safety Administration", 
"Treasury Department", 
"Internal Revenue Service", 
"U.S. House of Representatives", 
"United States Agency for Global Media", 
"United States Institute of Peace", 
"Veterans Affairs Department", 
"Women's Business Enterprise Interagency Committee", 
"Amazon", 
"Berkshire Hathaway", 
"Broadcom", 
"Eli Lilly", 
"Tesla", 
"JPMorgan Chase", 
"UnitedHealth (UNH)", 
"Exxon Mobil", 
"Oracle (ORCL)", 
"Mastercard (MA)", 
"Procter & Gamble (PG)", 
"Costco (COST)", 
"Home Depot (HD)", 
"Johnson & Johnson (JNJ)", 
"AbbVie (ABBV)", 
"Coca-Cola (KO)", 
"Bank of America", 
"Netflix", 
"Merck", 
"AMD", 
"Salesforce", 
"Chevron", 
"T-Mobile US", 
"Pepsico", 
"Adobe", 
"McDonald", 
"Cisco", 
"General Electric", 
"Danaher", 
"American Express", 
"Texas Instruments", 
"Caterpillar", 
"QUALCOMM", 
"Verizon", 
"Philip Morris", 
"ServiceNow", 
"Walt Disney", 
"Nextera Energy", 
"Intuit", 
"Amgen", 
"Intuitive Surgical", 
"Applied Materials", 
"Comcast", 
"Pfizer", 
"S&P Global", 
"Raytheon Technologies", 
"Goldman Sachs", 
"AT&T", 
"Lowe's Companies", 
"Union Pacific Corporation", 
"Progressive", 
"Booking Holdings (Booking.com)", 
"BlackRock", 
"Stryker Corporation", 
"Honeywell", 
"Nike", 
"TJX Companies", 
"Boston Scientific", 
"KKR & Co.", 
"ConocoPhillips", 
"Elevance Health", 
"Vertex Pharmaceuticals", 
"Arista Networks", 
"Micron Technology", 
"Citigroup", 
"Charles Schwab", 
"Prologis", 
"Analog Devices", 
"United Parcel Service", 
"Regeneron Pharmaceuticals", 
"Deere & Company", 
"Blackstone Group", 
"Automatic Data Processing", 
"Starbucks", 
"Marsh & McLennan Companies", 
"Palo Alto Networks", 
"American Tower", 
"Lam Research", 
"Gilead Sciences", 
"Bristol-Myers Squibb", 
"Fiserv", 
"Mondelez", 
"Southern Company", 
"Cigna", 
"Sherwin-Williams", 
"Boeing", 
"Southern Copper", 
"Intercontinental Exchange", 
"Duke Energy", 
"Zoetis", 
"Altria Group", 
"Moody's", 
"Colgate-Palmolive", 
"Palantir", 
"Waste Management", 
"General Dynamics", 
"Cintas", 
"Parker-Hannifin", 
"Airbnb", 
"Constellation Energy", 
"Synopsys", 
"TransDigm", 
"CME Group", 
"Chipotle Mexican Grill", 
"Illinois Tool Works", 
"Amphenol", 
"Welltower", 
"CVS Health", 
"3M", 
"Cadence Design Systems", 
"Freeport-McMoRan", 
"PNC Financial Services", 
"Carrier", 
"Ecolab", 
"Apollo Global Management", 
"Target", 
"U.S. Bancorp", 
"CrowdStrike", 
"Becton Dickinson", 
"EOG Resources", 
"GE Vernova", 
"CSX Corporation", 
"Air Products and Chemicals", 
"O'Reilly Automotive", 
"FedEx", 
"Enterprise Products", 
"McKesson", 
"Simon Property Group", 
"Republic Services", 
"Public Storage", 
"Emerson", 
"D. R. Horton", 
"Aflac", 
"Newmont", 
"Marvell Technology Group", 
"Credit One Bank", 
"FIS Global", 
"New Jersey Institute of Technology", 
"Alkami Technology", 
"Aerotech, Inc.", 
"Interstate Moving Relocation Logistics", 
"Lincoln Land Community College", 
"Santa Clara Valley Transportation Authority", 
"Metropolitan Transportation Authority", 
"Wipro Limited", 
"Virginia Commonwealth University", 
"Juniper Networks", 
"Naval Nuclear Laboratory", 
"StubHub", 
"Rivian", 
"NewsBreak", 
"Boston Scientific Corporation", 
"National Security Agency", 
"MUFG Bank, Ltd.", 
"Netsmart Technologies", 
"Medtronic", 
"f5", 
"Intellibee", 
"Automobile Club of Southern California", 
"Western Union", 
"Southside Va Community College", 
"Temple University", 
"ADP", 
"Ibotta", 
"University of Rochester", 
"Accenture Federal Services", 
"D365 Microsoft Partnership", 
"Digital Federal Credit Union / DCU", 
"Cognizant Technology Solutions", 
"NTT DATA", 
"JPMorganChase", 
"Benchmark Education Company", 
"American Physical Society", 
"Cambridge Technology Enterprises (CTE)", 
"Credit Acceptance", 
"Texas A&M University - San Antonio", 
"Cloud 9 Infosystems", 
"Firstlight Federal Credit Union", 
"Lennar", 
"Iowa 80 Truckstop", 
"ASRC Federal Holding Company", 
"Austin Peay State University", 
"Deluxe", 
"ECS Federal, LLC", 
"Hanscom Federal Credit Union", 
"Peloton", 
"Belay Technologies", 
"Autodesk", 
"Florida State College at Jacksonville", 
"Teradyne", 
"CEDENT", 
"Risk Solutions", 
"State of Ohio Jobs", 
"New York City Department of Education", 
"DraftKings", 
"Ada County", 
"NCR", 
"Education Department, State", 
"University of Idaho", 
"Raymond James Financial, Inc.", 
"University of New Hampshire", 
"Granite Telecommunications", 
"University at Albany", 
"GM Financial", 
"Disney Entertainment & ESPN Technology", 
"Scotiabank", 
"Fluidra North America", 
"Expedia Group", 
"Disney", 
"Citi", 
"TulaCo", 
"Sirius XM", 
"Adswizz", 
"d3v Technology Solutions", 
"Costco Wholesale", 
"PEPCO", 
"Virginia Tech", 
"Orbis", 
"NAVEX Global", 
"UST Global", 
"KUBRA", 
"Federal Client", 
"Laiba Technologies", 
"York Space Systems", 
"Merrick Bank", 
"State of Minnesota", 
"Taylor Corporation", 
"UKG", 
"College of Lake County", 
"San Bernardino County", 
"ByteDance", 
"Blue Cross of Idaho", 
"St. Catherine University", 
"State of Washington Dept. of Corrections", 
"California University Of Science And Medicine", 
"Kern County Superintendent Of Schools", 
"State of Wisconsin", 
"State of Wyoming", 
"Capital Region BOCES", 
"University of Kentucky", 
"ECS Federal LLC", 
"Utah State University", 
"Department of General Services", 
"Knight Federal Solutions Inc", 
"OpenGov", 
"MIDCONTINENT INDEPENDENT SYSTEM", 
"Tetra Tech", 
"CareFirst BlueCross BlueShield", 
"HHAeXchange", 
"ICF", 
"Avenu Insights & Analytics", 
"Benecard Services Inc.", 
"QTC Management, Inc.", 
"TRICARE", 
"Federal Aviation Administration (FAA) contractors", 
"Department of Defense contractors", 
"Health and Human Services contractors", 
"General Dynamics Mission Systems, Inc", 
"Booz Allen", 
"ManTech", 
"Missoula County", 
"CACI", 
"Two Six Technologies", 
"Skagit County", 
"Innovative Defense Technologies (IDT)", 
"Peraton", 
"KBR", 
"Steampunk", 
"Federal Aviation Administration contractors", 
"The Villages", 
"Urban Packaging Corp.", 
"Apixio", 
"Advanced Micro Devices, Inc.", 
"Verra Mobility", 
"TRICARE Management Activity", 
"U.S. Department of Agriculture contractors", 
"Federal Emergency Management Agency contractors", 
"Department of Homeland Security contractors", 
"CoBank", 
"Federal Home Loan Bank of Dallas", 
"State of Washington Employment Security Department", 
"The State of Oklahoma", 
"BOARD OF GOVERNORS of the FEDERAL RESERVE SYSTEM", 
"University of Washington", 
"North Wind Group", 
"Guidehouse", 
"L3Harris Technologies", 
"U.S. Department of Homeland Security (through Guidehouse and others)", 
"MIT Lincoln Laboratory", 
"NASA (through MIT Lincoln Laboratory and NASA contractors)", 
"US Bureau of Reclamation", 
"Federal Signal", 
"State of Texas", 
"General Dynamics Land Systems US", 
"State of Washington Administrative Office of the Courts", 
"Washington State Patrol", 
"CDC Foundation", 
"National Institutes of Health (NIH)", 
"Pinellas County Government", 
"T-Rex Solutions", 
"State Farm", 
"FSS Government Solutions", 
"Wespath Benefits and Investments", 
"CGI Group, Inc.", 
"DASNY - Dormitory Authority of the State of New York", 
"The MITRE Corporation", 
"State of Missouri", 
"USAA", 
"County of Santa Barbara", 
"Mayo Clinic", 
"Shriners Children's", 
"Trinity Health", 
"Veterans United Home Loans", 
"Saint Louis University", 
"NASPO", 
"State of Montana", 
"MS Dept. of Revenue", 
"City and County of San Francisco", 
"US Consumer Financial Protection Bureau", 
"Federal Reserve Bank of Boston", 
"State University of New York at New Paltz", 
"Johns Hopkins Applied Physics Laboratory (APL)", 
"Tarrant Regional Water District", 
"DAS Federal, LLC", 
"Department of Defense (DoD)", 
"US Federal Reserve Bank of Boston", 
"North Carolina A&T State University", 
"GEICO", 
"State of Colorado Job Opportunities", 
"METROPOLITAN WASHINGTON COUNCIL OF GOVERNMENTS", 
"POLICE DEPARTMENT", 
"City of Davenport", 
"Department of City Planning", 
"TEXAS EDUCATION AGENCY", 
"Nationwide IT Services", 
"Northwestern Memorial Healthcare", 
"Geisinger", 
"iDirect GOVERNMENT", 
"Pacific Northwest National Laboratory", 
"Los Alamos National Laboratory", 
"US Peace Corps", 
"Raytheon Technologies Corporate Headquarters", 
"City of San Antonio", 
"City of Sacramento", 
"NYC Office Of The Mayor", 
"San Francisco Health Plan", 
"City of El Paso, TX", 
"State of Idaho", 
"State of Louisiana", 
"State of New Mexico", 
"U.S. DHS Headquarters", 
"San Bernardino Superior Court", 
"U.S. District Court - Southern District of Georgia", 
"Lawrence Livermore National Laboratory", 
"Texas Workforce Commission", 
"State of Georgia", 
"City of Miami, FL", 
"California Governor's Office of Emergency Services", 
"City of Houston, TX", 
"Massachusetts School Building Authority", 
"Department of Med Assistance Svcs", 
"United Nations Federal Credit Union", 
"North Carolina Dept of Health and Human Services", 
"Metropolitan Transportation Commission", 
"Sacramento County Office of Education", 
"State of Utah", 
"State of Washington Parks and Recreation Commission", 
"Louisiana Supreme Court", 
"Government Tactical Solutions", 
"Texas Regional Bank", 
"North Dakota Office of Attorney General", 
"Experian", 
"Regions", 
"State of Washington Dept. of Commerce", 
"DEPARTMENT OF CORRECTION", 
"Lower Colorado River Authority", 
"Volusia County, FL", 
"Railroad Commission of Texas", 
"Texas A&M University", 
"Idaho National Laboratory", 
"Office of the Chief Financial Officer (OCFO)", 
"First American Financial Corporation", 
"Research Foundation for SUNY", 
"City of South Fulton", 
"Indiana Public Retirement System", 
"State of Arizona", 
"U.S. Bank National Association", 
"St. Mary's County Public Schools", 
"National Grid", 
"State of Arkansas", 
"Pantex", 
"DEPARTMENT OF TRANSPORTATION", 
"State of Washington State Board for Community & Technical Colleges (SBCTC)", 
"State of Maryland", 
"US Office of the Chief Economist", 
"Vanderbilt University Medical Center", 
"State of Indiana", 
"Serco North America", 
"NCR Atleos", 
"Delta Dental", 
"East West Bank", 
"Delta Dental of Missouri", 
"Edward Jones", 
"Ahold Delhaize USA", 
"First National Bank of America", 
"Athenahealth", 
"VeriskFieldprint", 
"Earth Space Technology Services, LLC", 
"Tensley Consulting, Inc.", 
"CTIS, Inc.", 
"Broadridge", 
"H&R Block", 
"International Paper", 
"Kimley-Horn", 
"Anthology, Inc.", 
"Donnelley Financial Solutions", 
"Syneos Health Commercial Solutions", 
"Parexel", 
"Red Hat, Inc.", 
"Paychex", 
"RedSail Technologies", 
"ImageTrend", 
"Red Bull", 
"Leading Path Consulting", 
"The Rawlings Group", 
"Changeis", 
"MEDLOGIX, LLC", 
"A-TEK Inc.", 
"Hinshaw & Culbertson", 
"SageSure", 
"EnergyCAP", 
"Snapchat", 
"Facebook App", 
"YouTube", 
"Neuralink", 
"TD Bank", 
"Governor’s Office of Land Use and Climate Innovation", 
"US Agricultural Marketing Service", 
"FINRA", 
"COMPTROLLER OF PUBLIC ACCOUNTS", 
"DEPT OF HEALTH/MENTAL HYGIENE", 
"North Carolina Department of Information Technology", 
"Connect for Health Colorado", 
"The City University of New York (CUNY)", 
"Region 10 Education Service Center", 
"New York State Environmental Facilities Corporation", 
"New Jersey Courts", 
"Environmental Facilities Corporation", 
"Hennepin County", 
"City of Philadelphia", 
"DMV IT Service", 
"County of Monmouth", 
"DeKalb CUSD #428", 
"Michigan Court of Appeals", 
"Metropolitan Police Department", 
"Purdue University", 
"Jacksonville Sheriff's Office", 
"Keck Medical Center of USC", 
"Center for Internet Security, Inc.", 
"City of Mt. Pleasant", 
"Florida Department of Highway Safety and Motor Vehicles", 
"The Christian and Missionary Alliance", 
"Public Partnerships LLC", 
"Summit Technologies, Inc.", 
"Evolver Inc", 
"Douglas County, KS Government", 
"Ivy Tech Community College", 
"ADMIN FOR CHILDREN'S SVCS", 
"Jeffco Public Schools", 
"Harris County", 
"Stanford Health Care", 
"MIT", 
"Vanguard", 
"Stifel", 
"gWorks", 
"NYC IT Inc", 
"City of Tyler", 
"City National Bank", 
"PayPal", 
"Sigma Defense", 
"Banner Bank", 
"International SOS", 
"Toyota", 
"Varo Bank", 
"Worldpay", 
"Mobility USA", 
"Lenovo", 
"MongoDB", 
"Udacity", 
"TowneBank", 
"DISH", 
"Snowflake", 
"University of Utah", 
"AMETEK, Inc.", 
"Department of Health Care Access and Information", 
"NOKIA", 
"M&T Bank", 
"Intone Networks", 
"Zendesk", 
"Flagstar Bank", 
"City of Austin", 
"TransUnion", 
"University of Michigan", 
"Robert Half", 
"SS&C", 
"Conduent State & Local Solutions, Inc", 
"Fulton Bank", 
"Fifth Third Bank", 
"City of Chicago", 
"Lowe's", 
"DHL", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"DTS America", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Qode", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Priority Technology Holdings, LLC", 
"St Jardins", 
"Aescape", 
"Radiant Digital", 
"Cornell Pump Company LLC", 
"GD Resources", 
"Domino's Corporate", 
"ABC COMPANIES", 
"Skilled Workforce", 
"NxtWave Disruptive Technologies Private Limited", 
"Re:Build Manufacturing", 
"TradeStation", 
"Gov Services Hub", 
"Mercor: OpenAI", 
"R.E. Michel Company, LLC", 
"Fincons.US, Inc.", 
"SimpliSafe", 
"Realtor.com Careers", 
"CFO Advisors", 
"Thalo Labs", 
"Aspira Connect", 
"C&A Associates", 
"JumpCloud", 
"Mitsubishi Electric US, Inc.", 
"Captions", 
"Hawthorn Bank", 
"Nestlé IT", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Priority Technology Holdings, LLC", 
"St Jardins", 
"Aescape", 
"Radiant Digital", 
"Cornell Pump Company LLC", 
"GD Resources", 
"Domino's Corporate", 
"ABC COMPANIES", 
"Skilled Workforce", 
"NxtWave Disruptive Technologies Private Limited", 
"Re:Build Manufacturing", 
"TradeStation", 
"Gov Services Hub", 
"Mercor: OpenAI", 
"R.E. Michel Company, LLC", 
"Fincons.US, Inc.", 
"SimpliSafe", 
"Realtor.com Careers", 
"CFO Advisors", 
"Thalo Labs", 
"Aspira Connect", 
"C&A Associates", 
"JumpCloud", 
"Mitsubishi Electric US, Inc.", 
"InvestCloud", 
"MoEngage Inc", 
"ResQ", 
"NICE", 
"Lucid Motors", 
"Emovis", 
"Tekcogno", 
"National Testing Network", 
"Modernizing Medicine, Inc.", 
"NICE", 
"Global Payment Holding Company", 
"Eco Material Technologies Inc", 
"Drone Powered Solutions", 
"Interactive Brokers", 
"Emovis US", 
"Lucid Motors", 
"Powersolv", 
"TP-Link Systems Inc.", 
"TwelveLabs", 
"Holman", 
"Cvent", 
"Design Interactive", 
"CaringBridge", 
"FanDuel", 
"Asphalt Buyer II LLC", 
"MetroStar", 
"Parker Group Inc", 
"TwelveLabs", 
"Parker Group Inc", 
"Rhombus", 
"PHOTRONICS INC", 
"Bandwidth", 
"Acuity Inc.", 
"Travis County", 
"LaunchDarkly", 
"Zayo Careers", 
"G2i Inc.", 
"Kipsu", 
"CEF Solutions Inc.", 
"absiusa", 
"IvoryCloud", 
"Tekcogno", 
"TeleWorld Solutions Inc", 
"School Employees Retirement System of Ohio", 
"TwelveLabs", 
"ADB Safegate", 
"Hexagon Safety & Infrastructure", 
"PHOTRONICS INC", 
"Cvent", 
"Nationwide", 
"TP-Link Systems Inc.", 
"AppFolio", 
"i3 Verticals", 
"UPMC", 
"HTX Labs", 
"BTI Solutions, Inc.", 
"Parker Group Inc", 
"Asphalt Buyer II LLC", 
"Keysight Technologies", 
"Same", 
"Dun & Bradstreet", 
"Ford Motor Company", 
"Department of Taxation", 
"ERPA", 
"MetroStar", 
"Signify", 
"Dataquad Inc", 
"Photon", 
"Kipsu", 
"CEF Solutions Inc.", 
"absiusa", 
"Tech-assist", 
"IvoryCloud", 
"Tekcogno", 
"TeleWorld Solutions Inc", 
"School Employees Retirement System of Ohio", 
"TwelveLabs", 
"ADB Safegate", 
"PHOTRONICS INC", 
"Cvent", 
"Nationwide", 
"TP-Link Systems Inc.", 
"AppFolio", 
"i3 Verticals", 
"UPMC", 
"HTX Labs", 
"BTI Solutions, Inc.", 
"Woongjin, Inc", 
"Parker Group Inc", 
"Asphalt Buyer II LLC", 
"Tangle Systems", 
"Keysight Technologies", 
"Same", 
"Dun & Bradstreet", 
"Ford Motor Company", 
"Department of Taxation", 
"ERPA", 
"MetroStar", 
"Signify", 
"Photon", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"DTS America", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Priority Technology Holdings, LLC", 
"St Jardins", 
"InfStones", 
"Aescape", 
"Radiant Digital", 
"Cornell Pump Company LLC", 
"GD Resources", 
"Domino's Corporate", 
"ABC COMPANIES", 
"Skilled Workforce", 
"NxtWave Disruptive Technologies Private Limited", 
"Re:Build Manufacturing", 
"TradeStation", 
"Gov Services Hub", 
"Mercor: OpenAI", 
"R.E. Michel Company, LLC", 
"Fincons.US, Inc.", 
"SimpliSafe", 
"Realtor.com Careers", 
"CFO Advisors", 
"Thalo Labs", 
"Aspira Connect", 
"C&A Associates", 
"JumpCloud", 
"Mitsubishi Electric US, Inc.", 
"InvestCloud", 
"MoEngage Inc", 
"ResQ", 
"NICE", 
"Lucid Motors", 
"Emovis", 
"Tekcogno", 
"National Testing Network", 
"Modernizing Medicine, Inc.", 
"NICE", 
"Global Payment Holding Company", 
"Eco Material Technologies Inc", 
"Interactive Brokers", 
"Emovis US", 
"Lucid Motors", 
"Powersolv", 
"TP-Link Systems Inc.", 
"TwelveLabs", 
"Holman", 
"Cvent", 
"Design Interactive", 
"CaringBridge", 
"FanDuel", 
"Asphalt Buyer II LLC", 
"MetroStar", 
"Parker Group Inc", 
"TwelveLabs", 
"Parker Group Inc", 
"Rhombus", 
"PHOTRONICS INC", 
"Bandwidth", 
"AmeriLux International", 
"Auxiant", 
"Quora", 
"First Community Credit Union", 
"E Source", 
"NBCUniversal", 
"Excellent Opportunity", 
"ServiceTitan, Inc.", 
"Asure Software", 
"Tempo Software Inc.", 
"Cheil Dallas", 
"HR Elements", 
"Royal Markets Inc.", 
"IDT", 
"VetsEZ", 
"Sparibis", 
"Asure Software", 
"Innodata Inc", 
"Honda", 
"GATEKEEPER SYSTEMS", 
"ABB", 
"Liberty Mutual", 
"Calendly", 
"Flatfile", 
"Simplot", 
"Piper Companies", 
"Karat", 
"Johnson & Johnson", 
"Publix", 
"Piper Companies", 
"Annapurna Labs (U.S.) Inc.", 
"General Motors", 
"American Sugar Refining", 
"Argano", 
"The Travelers Companies, Inc.", 
"Honda Research Institute USA", 
"EvenUp", 
"Information Technology Senior Management Forum", 
"Piper Companies", 
"CooperSurgical", 
"COPE Health Solutions", 
"Progyny, Inc", 
"Briljent", 
"Texas Health and Human Services Commission", 
"Lambda", 
"Information Technology Senior Management Forum", 
"Air Methods", 
"UCF", 
"American Sugar Refining", 
"SALT LAKE CITY CORP", 
"Bureau Veritas", 
"Labcorp", 
"Photon", 
"Optum", 
"DSFederal, Inc.", 
"DigitalOcean", 
"NRG Energy, Inc", 
"ATHES", 
"Unify", 
"Anblicks", 
"JCB North America", 
"The First National Bank & Trust Co", 
"Simon & Schuster", 
"Muckleshoot Casino Resort", 
"Intratek Computer, Inc.", 
"Hyundai Autoever America", 
"Handshake", 
"Best High Technologies PVT LTD", 
"Radix", 
"Publicis Groupe", 
"T-Mobile USA, Inc.", 
"Nestlé Purina", 
"Disney Entertainment and ESPN Product & Technology", 
"Tulane University", 
"SAP", 
"CNO Financial Group", 
"SSA Marine, Inc", 
"Rockwell Automation", 
"University of Alabama, Birmingham", 
"Fujifilm", 
"Republic National Distributing Company", 
"BlackRock Investments", 
"Philips", 
"Nestlé Purina", 
"Grindr", 
"Mozilla", 
"PGIM", 
"Elsevier", 
"Hofstra University", 
"Tulane University", 
"Illinois Institute of Technology", 
"Hewlett Packard Enterprise", 
"Frederick National Laboratory", 
"OpenAI", 
"NICE Systems", 
"Solventum", 
"Lumen", 
"Inter-American Development Bank", 
"Fidelity National Information Services", 
"Nestlé USA", 
"Prince Willam Water", 
"Southeast Alaska Regional Health Consortium", 
"Logix Federal Credit Union", 
"Popular Bank", 
"Indiana University", 
"E-Business International", 
"Amazon.com", 
"Handshake", 
"Red Robin International, Inc.", 
"Archer", 
"tvScientific", 
"Handshake", 
"SOUTH COLLEGE", 
"University of Maryland Medical System", 
"D. Kent Consulting Group, LLC", 
"New Mexico State University Foundation Inc", 
"Apria Healthcare LLC", 
"evlos", 
"Nextdoor", 
"Ema", 
"LendingClub Bank, N.A.", 
"World Wide Technology Holding, LLC", 
"E-Solutionts", 
"Point Broadband", 
"U.S. LawShield", 
"Chamberlain University", 
"Adtalem Global Education", 
"SwitchThink Solutions LLC", 
"Rectorseal", 
"Oran Inc", 
"Protect Life Michigan", 
"RevenueCat", 
"GovTact", 
"Power3 Solutions and Partnering Companies", 
"Ascension Federal Services Inc.", 
"Veterans Sourcing Group", 
"LendingPoint, LLC", 
"Samsung Research America", 
"Pattison ID", 
"NFI Industries", 
"American Nurses Association ANA", 
"XPRESSDOCS PARTNERS, LTD.", 
"Themis Insight", 
"Snapsheet", 
"Southminster Inc", 
"Outpower Energy Corp.", 
"Anduril Industries", 
"NFI Industries", 
"Thetford LLC & Norcold LLC", 
"Oil-Dri Corporation of America", 
"CSAT Solutions", 
"Cilable", 
"Govini", 
"Stand Together", 
"Kaizen Dynamics", 
"GenTech Associates", 
"Resource Management Associates, LLC", 
"Datalab USA", 
"Hudson Manpower", 
"Cross River", 
"MSX International", 
"Cross River", 
"Baker Tilly Advisory Group, LP", 
"STAT9 Technologies", 
"Resource Management Associates, LLC", 
"American Technology Experts Inc", 
"MIT Federal Credit Union", 
"Asurion", 
"Park Community Credit Union", 
"INFRANERGY", 
"Vetrics Group", 
"Tulsa Public Schools", 
"Beacon Credit Union - Indiana", 
"Ascella Technologies, Inc.", 
"MVK TECH", 
"Infoorigin Inc", 
"App Maisters Inc", 
"MVK TECH", 
"Indiana Legal Services, Inc.", 
"BankUnited", 
"The George Washington University Hospital", 
"Success Academy Charter Schools", 
"Hogue, Inc.", 
"ElevenLabs", 
"LOANBUD INC", 
"ELEVI Associates", 
"IMG Academy", 
"Aaditus Technologies LLC", 
"BitGo", 
"TMP Worldwide India Private Limited for ERS US", 
"Tamayo Federal Solutions LLC", 
"Delta Star Inc.", 
"Silco Fire & Security", 

]