
# jobs page urls for listing all jobs first
jobs_listed_pages_urls = [
# "https://www.indeed.com/jobs?q=power+bi+analyst&l=United+States&fromage=1&from=searchOnDesktopSerp&vjk=f6fec11c6cb0b807",
# "https://www.indeed.com/jobs?q=data+scientist&l=United+States&fromage=1&from=searchOnDesktopSerp&vjk=921edb4b120e47ac",
# "https://www.indeed.com/jobs?q=machine%20learning%20engineer&l=United%20States&fromage=1&from=searchOnDesktopSerp",
# "https://www.indeed.com/jobs?q=deep%20learning&l=United%20States&fromage=1&from=searchOnDesktopSerp",
# "https://www.indeed.com/jobs?q=analytics+engineer&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=58a9f0610cc52841",
# "https://www.indeed.com/jobs?q=artificial+intelligence&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=7cb4140c5710b59b",
# "https://www.indeed.com/jobs?q=etl+developer&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=43928fe71aedfd20",
# "https://www.indeed.com/jobs?q=mlops&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=1a720386f4d7bcc3",
# "https://www.indeed.com/jobs?q=databricks&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=9027abd1668d6bcd",
# "https://www.indeed.com/jobs?q=azure+cloud+engineer&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=f8ef3fb4d7b56898",
# "https://www.indeed.com/jobs?q=nlp&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=1a720386f4d7bcc3",
# "https://www.indeed.com/jobs?q=matlab&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=ce081b994d4e554b",


"https://www.indeed.com/jobs?q=transformer&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=a8e33be9c8ab431a"
"https://www.indeed.com/jobs?q=computer+vision&l=USA&fromage=1&from=searchOnDesktopSerp&vjk=8bf2b28241529eeb",
"https://www.indeed.com/jobs?q=nlp&l=United%20States&fromage=1&from=searchOnDesktopSerp",
"https://www.indeed.com/jobs?q=python%20developer&l=United%20States&fromage=1&from=searchOnDesktopSerp",
"https://www.indeed.com/jobs?q=mlops&l=United%20States&fromage=1&from=searchOnDesktopSerp",
"https://www.indeed.com/jobs?q=tensorflow&l=United%20States&fromage=1&from=searchOnDesktopSerp",
"https://www.indeed.com/jobs?q=pytorch&l=United+States&fromage=1&from=searchOnDesktopSerp&vjk=33d65538b54dd489",
"https://www.indeed.com/jobs?q=data+engineer&l=United+States&fromage=1&from=searchOnDesktopSerp&vjk=65049515d961f17e",
"https://www.indeed.com/jobs?q=etl%20developer&l=United%20States&fromage=1&from=searchOnDesktopSerp"
"https://www.indeed.com/jobs?q=ai%20testing&l=United%20States&fromage=1&from=searchOnDesktopSerp",
"https://www.indeed.com/jobs?q=analytics%20engineer&l=United%20States&fromage=1&from=searchOnDesktopSerp",
"https://www.indeed.com/jobs?q=ai%20engineer&l=United%20States&fromage=1&from=searchOnDesktopSerp",
"https://www.indeed.com/jobs?q=statistical%20analyst&l=United%20States&fromage=1&from=searchOnDesktopSerp",

]

MATCHING_PERCENTAGE = 50
leave_blank_colls = 2


# In below var we will gave prompt to ai for geting specfic task for now as matching % for each jobs
AI_PROMPT = """
Based on the resume below, give the **highest match percentage** for each job title in a single line of space-separated numbers. No explanations, just numbers like:
95 85 30 65...
Resume:
"""

# resume for ai to provide every jobs matching % base one resume
RESUME = """
AI/ML & Data Science expert with experience in NLP, CV, and analytics. Skilled in Python, Go, SQL, PyTorch, TensorFlow, and ML tools (Scikit-learn, Hugging Face, XGBoost). Hands-on with LLMs, LangChain, AutoGPT, RAG, and model optimization. Proficient in MLOps (Docker, Kubernetes, Airflow, MLflow), cloud (AWS, GCP, Azure), and data engineering (Spark, Hive, Snowflake). Experienced in REST APIs, vector DBs (FAISS, Weaviate), and Agile teams.
"""

#
per_company_jobs = 2


# ON/OFF Headless mode
headless = True

# File path which jobs processed 
PROCESSED_JOBS_FILE_PATH =r'input\\processed_jobs.txt'

# after extract jobs from list page size of batche should be process and saving excel file
process_batch = 15

# Wait until pagination appears before rasing not found error
wait_pg_present = 6

# Excel file path
EXCEL_FILE_PATH = r'output\\jobs.xlsx'


DEBUGGING_SCREENSHOTS_PATH = "debugging_screenshots"

#
leave_blink_cols = 2

# These file are append with scraping data during scraping
CSV_FILES = ["Easy_applies.csv", "CS_applies.csv", "Confirmation_applies.csv"]


# workbook id
workbook_id = "1wgGWS5xvxJgOuf2rx3TLQNDYSNStttQa7L8fFSWxs30"

# give permission as editor this below mail
"python-api@indeed-leads-467810.iam.gserviceaccount.com"
confirmation_companies = [
"DeveloperTown",
"Youth Villages",
"Ironside Group",
"YouLend",
"BSC Analytics",
"Selby Jennings",
"Confiz",
"Onco360",
"Suralink Inc",
"The Contractor Consultants",
"Tantus Technologies",
"Navitus Health Solutions, LLC",
"KENT Corporation(Kent Global Business Services",
"Sage Dental",
"Medius",
"MECCO.",
"HealthVerity",
"CCC Intelligent Solutions Inc.",
"Jenzabar",
"Yardi Systems, Inc.",
"Rhythmos",
"Crossvale, Inc.",
"RouteSmart Technologies Inc",
"T2 Systems",
"Capstone Logistics LLC",
"Occam Design",
"Catalyst Health Group",
"RainesDev",
"Aquila Software Group",
"SiteOne Landscape Supply",
"Crunchtime",
"LineLeader",
"West Coast Wound and Skin Care",
"Inspira Financial",
"Levi, Ray & Shoup, Inc.",
"tally health company",
"Apiture",
"SphereCommerce",
"slb",
"GEICO",
"Tapcheck Inc.",
"WP Engine",
"Amwins Group, Inc.",
"Insperity",
"Hired By Matrix",
"CYPHER Learning",
"CHS Corporate",
"Qlik",
"Bridgestone Americas",
"QSR Automations Inc",
"ActiveCampaign",
"Sanford Health",
"Blueprint Technologies",
"Bullhorn",
"Matrix Design Group",
"One Inc Software Corporation",
"S Of I Consulting Group Llc",
"GeoVera Holdings",
"AccentCare, Inc.",
"VISTRUE LLC",
"Lighthouse Document Technologies Inc/(Lighthouse)",
"Pure Recruiting Agency",
"Musco Sports Lighting",
"Forward Edge-AI Inc",
"Who's Got Game",
"Welbehealth",
"Leepfrog Technologies Inc",
"Sun Communities, Inc.",
"Trustmark",
"CPI Card Group",
"Alliance Technical Group",
"NAIC",
"Business Risk Partners",
"Enghouse",
"LIGHTFEATHER IO LLC",
"PTS Advance,anvilcorp",
"BigTime Software",
"Fullsteam",
"Travoom",
"BonCor Medical",
"Centeva",
"Paradigm Inc.",
"Scrapbook.com",
"Puzzle Solutions Holdings LLC",
"Purpose Financial",
"Link Munch",
"Qlik",
"PrismHR",
"HCA Healthcare",
"3Box Labs",
"KNOWiNK",
"iA",
"Wegmans",
"Framatome",
"Schneider Electric",
"Carhartt",
"Musco Olive Products",
"The Chamberlain Group LLC",
"Shapeways",
"Meduit",
"TruStage",
"Spry Digital",
"ArborNoteSoftware",
"Birkman International",
"WeInform",
"Clutchnow",
"AMOpportunities",
"R&R Partners",
"CATIC",
"inVesti",
"Eclips Reality",
"Tespo",
"AdviNow",
"Emtec Global Services",
"KSA&D",
"KSA&D, Inc",
"PerigonHealth360",
"John Deere",
"SocialBridge Technologies",
"SocialBridge",
"Birkman International",
"Dynafios",
"Veriforce",
"Paycor",
"Bizfolio",
"TCC Solutions",
"Celebration Marketing",
"Sourcewerx, Inc",
"Value Wholesale Distributors",
"Gomocha",
"EPIC Brokers",
"Health in Tech",
"Cannae HR Solutions",
"Cardinal Glass Industries",
"Visionary WebDZ, Inc",
"Batteries Plus",
"Pinnacle USA, Inc.",
"Pinnacle",
"Media Fit LLC",
"Saince",
"Candor Technology",
"Yume",
"Media Fit",
"LivePerson",
"Live Person",
"Proguard",
"Proguard Warranty Inc",
"Social Bridge technologies",
"AAIT Health RCM",
"Social Bridge Tech",
"MetriTech, Inc",
"Metri Tech",
"Pain treatment center",
"Social Bride",
"Trialogics",
"Sintesys",
"MobileDealer",
"We Inform",
"Designing Success",
"We Inform LLC",
"Open Core Ventures",
"WisePelican",
"Lifeboost",
"Palletfly.com LLC",
"InnoWave",
"Dolphin Entertainment, LLC",
"Perigonhealth",
"Mermaid Chart",
"Citizenopolis",
"BrickSimple",
"SADA",
"Brick Simple",
"Media.Monks",
"StackBuilders",
"Audentio",
"Citizenly",
"Kastel Staffing Group",
"Elite Business Solutions",
"handles the human resources",
"payroll and benefits",
"3CInstitute",
"Konane Solutions",
"O3World",
"Corridor",
"Haulink LLC",
"AccentureFlex",
"MNK INFOTECH",
"Ndevr",
"Emtec",
"Amida Technology Solutions",
"mcgaw",
"HeroDevs",
"BoviSync",
"Melon",
"Srijan Technologies",
"InfoMagnus",
"Pallet Fly",
"Swell LLC",
"Text Connects",
"FiscalNote",
"Destination Pet LLC",
"L1 PET HOLDINGS (USA) LLC",
"mysamaris",
"Say I Do At The Altar",
"Growmark",
"insite",
"olympusat",
"RINGLEADER, INC.",
"GRIFFIN Solutions Group",
"Kastel",
"BackOffice Staffing Solutions",
"Back Office Staffing Solutions",
"Kastel Staffing Group",
"BOSS",
"Hiedrick and struggles",
"DrFirst Inc.",
"SuperSonic POS / Petro Outlet",
"Avant Assessment LLC",
"Avant",
"Think Company",
"ACES Quality Management",
"Recall Masters, Inc.",
"Maxiom",
"ORPICAL",
"Crowdkeep",
"Korio",
"RehabPath",
"IP Pathways",
"Accelerated Global Solutions, Inc.",
"Accelerated Global Solutions",
"Speedx",
"AGS",
"Main Street, Inc.",
"WOrMS Connect",
"It Works Marketing, Inc",
"TSL Companies",
"Attics and More, Inc",
"Full Spectrum",
"Galloping Digital, Inc",
"FYX Fleet",
"AssistRx",
"Dunavant Logistics",
"Blue Label Labs",
"Kraemer Schurman Advertising & Design (KSA&D)",
"BlueLabel",
"Hot Leads",
"AMN Healthcare",
"Combined Insurance",
"Adaptelligence",
"Ligosports",
"Full Spectrum Software",
"Full Spectrum",
"High Priority Leads",
"ClearTrack HR",
"smart Steel Technologies",
"Priority Leads",
"Arine",
"Quality Counts LLC",
"LPL Financial",
"ClaimGem",
"Torch",
"FINCONS",
"America's Test Kitchen",
"MedaSync",
"IQ Solutions Inc",
"The Real Estate Technology Institute",
"Artix Entertainment LLC",
"CircleLink Health",
"ETHANY Corporation",
"ASCEND HIT LLC",
"It Works Marketing, Inc.",
"California Closets",
"Munera Inc.",
"Engrain",
"Envisionit",
"Bounteous",
"Metis Consulting Group",
"Base22",
"GoX Labs",
"NinjaTrader",
"Tevpro",
"Syndica",
"Metova, Inc",
"Insurium",
"Good Leads",
"Lynx Analytics",
"Returnmates",
"OK Capsule",
"Spokeo",
"Conversio Health",
"Perficient",
"Pivotal Talent Search",
"Beezwax",
"Rockhopper Tech",
"Tabula Rasa HealthCare",
"A.J. Boggs & Company",
"Ecosystem Planning and Restoration, LLC",
"BubbleUp",
"Positive Development",
"Therapy Management Corporation",
"Jahnel Group",
"HomeWorks Energy",
"Accuhealth",
"NexGen",
"Aperia",
"VES",
"Radancy",
"Pringle Technologies Inc",
"GetBusy",
"VTS - Virtual Technology Simplified",
"RGC Digital",
"Perspective Developers",
"Elevate Healthcare Marketing",
"Adapt",
"qosconsulting",
"Somatus",
"NinjaHoldings",
"Aledade",
"Journeys Metabolic",
"Olo",
"Metrohm Raman",
"FreeStar",
"MCG Health",
"Stack AV",
"OrbitalRx",
"FutureWise",
"AccelerEd",
"Habitat Energy",
"FutureWise Insurance Agency",
"iFIT",
"ReferWell",
"myLaurel",
"IT Labs",
"Pivot Group",
"Squadformers",
"Vermill.io",
"CareDx",
"DoMyOwn",
"GEICO",
"Kavaliro",
"Trulieve",
"Vermill",
"AVM Consulting",
"Mentor Talent Acquisition",
"Clutch",
"ADTRAV",
"Breakout EDU",
"Artisys Corporation",
"Akvelon Recruiter",
"Asset Watch",
"AssetWatch",
"Equidox Software Company",
"Clutchnow (inVesti)",
"Kavaliro (Trulieve)",
"Merkle",
"CURO",
"MajorBoost",
"Breakout EDU",
"Gideon Taylor Consulting LLC",
"Ulta Beauty",
"Affiliated Monitoring",
"Dexcom",
"Ancestry",
"Hummingbirds Innovations",
"Vital Tech Solutions",
"Partnership Employment",
"VTS",
"Virtual Technology Simplified",
"Dentsu",
"Major Boost",
"TixTrack",
"First Fertility",
"Tempus",
"ePayPolicy",
"Nomad eCommerce",
"Leap Orbit LLC",
"Paradigm Health",
"VanNoppen Marketing",
"QuickVisit Urgent Care",
"MATRIX SYSTEMS & TECHNOLOGIES INC",
"Monogram Health Inc",
"lalaith astor technical",
"Nest Health",
"COMPLY",
"AxisCare",
"Gateway ticketing systems, inc.",
"Healthmark Group",
"Converging Resources Corporation",
"Praxent",
"Cascade Energy, LLC",
"Trademasters Services",
"Investview Inc.",
"iQuasar, LLC",
"Pushnami",
"SmartDraw Software, LLC",
"GRAIL",
"Oshi Health",
"Ranken-Jordan Home For Convalescent",
"Mr.Ben",
"Skye Bond",
"Mark Sulzen",
"Anita Arroyo",
"Dwight Scott",
"Lauren Villanueva",
"Joan Yohn",
"Owen Walsh",
"Lawrence Paranidharan",
"Gia Sharda",
"Buddy Wilkins",
"Kyle Szombathy",
"Shapeways",
"Meduit",
"TruStage",
"TixTrack",
"First Fertility",
"Tempus",
"ePayPolicy",
"Nomad eCommerce",
"Leap Orbit LLC",
"Paradigm Health",
"VanNoppen Marketing",
"QuickVisit Urgent Care",
"MATRIX SYSTEMS & TECHNOLOGIES INC",
"Monogram Health Inc",
"lalaith astor technical",
"Nest Health",
"COMPLY",
"AxisCare",
"Gateway ticketing systems, inc.",
"Healthmark Group",
"Converging Resources Corporation",
"Praxent",
"Cascade Energy, LLC",
"Trademasters Services",
"Investview Inc.",
"iQuasar, LLC",
"Pushnami",
"SmartDraw Software, LLC",
"GRAIL",
"Oshi Health",
"Ranken-Jordan Home For Convalescent",
"Millers Mutual Group",
"Downeast Cider House",
"PeritusHub LLC",
"Navan",
"Fortegra",
"SkySlope",
"PeritusHub LLC",
"Navan",
"Fortegra",
"SkySlope",
"Comfy Org",
"Rippling",
"Odyssey",
"Rippling",
"Odyssey",
"Kenco Management Services LLC",
"Sage Care Inc",
"Ambient.ai",
"Genmo",
"Aparavi",
"TextLayer",
"Duranta",
"Valkyrie Intelligence",
"Comfy",
"Genmo",
"TextLayer",
"Duranta",
"Valkyrie Intelligence",
"Root Access",
"Echo Neurotechnologies",

]

# list of companies to ignore for instance like : apple, amazon, google etc
ignore_companies = [
    "Lila Sciences, Inc.",
    "Academy Automobile Insurance Services, Inc.",
    "Ellumen",
    "Academy Automobile Insurance Services, Inc.",
    "BB6 Defense",
    "University Support Services, an Affiliate of St. George's University",
    "Capio Group",
    "Eagle Community Credit Union",
    "Preferred Equipment, LLC",
    "Academy Automobile Insurance Services, Inc.",
    "Dent Neurologic Group LLP",
    "BB6 Defense",
    "University Support Services, an Affiliate of St. George's University",
    "Atlas Technologies Inc",
    "Capio Group",
    "ProntoDigital LLC",
    "Dfuse Technologies, Inc.",
    "Eagle Community Credit Union",
    "Eagle Community Credit Union",
    "ADNET Systems, Inc.",
    "Info Origin",
    "Atlas Technologies Inc",
    "United Way of Greater Cincinnati",
    "Atlas Technologies Inc",
    "Joint Research and Development, LLC",
    "iTech Solutions Pvt. Ltd.",
    "Dfuse Technologies, Inc.",
    "Millennium Physician Group",
    "Landmark Structures",
    "CreativeWolf Agency & BlackSeed Labs",
    "Millennium Physician Group",
    "Atlas Technologies Inc",
"Natcast",
"TechSur Solutions",
"CSCI Consulting",
"Shield Consulting Solutions",
"First Fed",
"Spalding",
"Ancilla Technologies & Services, Inc.",
"Samsung Research America Internship",
"Intezra, Inc.",
"AnaVation",
"TaxHawk Inc",
"Binance",
"Intepros Federal",
"WinChoice USA",
"Aalis Management Consulting",
"Shield Consulting Solutions",
"HCA Healthcare", 
"Sumitomo Mitsui Banking Corporation", 
"KeyBank National Association", 
"Infosys", 
"Zoom", 
"Hilton Grand Vacations", 
"Coinbase", 
"Twilio", 
"Gusto", 
"Gainwell Technologies", 
"TEKsystems", 
"Ascensus", 
"ESRI", 
"Northrop Grumman Corporation", 
"Capgemini", 
"DocuSign", 
"Almac Group", 
"Rocket Lab USA", 
"UPS", 
"Marriott International", 
"Cisco Meraki", 
"Walmart", 
"Ltimindtree", 
"Mastercard", 
"e business international inc",
"Accenture", 
"Equinix", 
"ALTEN Technology", 
"Bloomberg", 
"Apple", 
"Meta", 
"Alphabetic Inc", 
"ExxonMobil", 
"Uber", 
"Federal & Government-Related Organizations:", 
"Association of Universities for Research in Astronomy", 
"SteerBridge Strategies", 
"Bank", 
"Port Technology Services", 
"University", 
"College", 
"KPMG", 
"Blue Origin", 
"IBM", 
"Dell", 
"Hitachi", 
"Sony", 
"Intel", 
"Siemens", 
"TCS", 
"Nestlé", 
"Spotify", 
"Microsoft", 
"Fox Corporation", 
"Liberty Mutual Insurance", 
"Motorola Solutions", 
"Samsung", 
"Mutual of Omaha", 
"Nasdaq", 
"Okta", 
"Visa", 
"Atlassian", 
"Siemens Industry Software Inc.", 
"Toshiba", 
"Panasonic Corporation", 
"Oracle", 
"Thermo Fisher Scientific", 
"Motorola", 
"eBay", 
"GoDaddy", 
"WebMD", 
"Indeed", 
"Gartner", 
"Capital One", 
"Discord", 
"NVIDIA", 
"Amazon.com Services LLC", 
"Amazon Development Center U.S., Inc.", 
"Royal Bank of Canada", 
"Amazon Data Services, Inc.", 
"Google", 
"Amazon Web Services, Inc.", 
"Capgemini Engineering", 
"Amex", 
"Sam's Club", 
"PlayStation Global", 
"NIH-NCBI", 
"United States Senate Sergeant at Arms", 
"floridadep", 
"Lockheed Martin", 
"PricewaterhouseCoopers (PWC)", 
"Khan Academy", 
"American Airlines", 
"Morgan Stanley", 
"BNY Mellon", 
"Nissan", 
"Workday", 
"KLA", 
"Safran", 
"Georgia-Pacific", 
"Mizuho Americas", 
"Twitch", 
"Sallie Mae", 
"Abbott Laboratories", 
"Saab Inc.", 
"McAfee, LLC", 
"United Airlines", 
"Wells Fargo", 
"Fidelity Investments", 
"Northrop Grumman", 
"RTI International", 
"Deloitte", 
"General Dynamics Information Technology", 
"Comcast Corporation", 
"HII", 
"Roblox", 
"Federal Reserve Bank of St. Louis", 
"Blackhawk Network", 
"Blue Cross Blue Shield Association", 
"Textron Aviation", 
"SAIC", 
"Spectrum", 
"Cognizant", 
"Navy Federal Credit Union", 
"Truist Bank", 
"Leidos", 
"Cisco Systems", 
"Collins Aerospace", 
"Teledyne Technologies Inc.", 
"CoStar Group", 
"Trane Technologies", 
"City of Davenport, IA", 
"City of Chesapeake", 
"St Johns River Water Management District", 
"South Dakota Board of Regents", 
"Capital Area Intermediate Unit", 
"University of Maryland", 
"State of Delaware", 
"The State of Florida", 
"Douglas County, CO", 
"The University of Chicago", 
"University of Notre Dame", 
"Maricopa Community Colleges", 
"Qorvo", 
"Tria Federal (Tria)", 
"TSPi", 
"The GBS Group", 
"None explicitly listed", 
"Defense Department", 
"Air Force Department", 
"Army Department", 
"Defense Acquisition Regulations System", 
"Defense Contract Audit Agency", 
"Defense Information Systems Agency", 
"Defense Intelligence Agency", 
"Defense Investigative Service", 
"Defense Logistics Agency", 
"Defense Mapping Agency", 
"Defense Special Weapons Agency", 
"Engineers Corps", 
"National Geospatial-Intelligence Agency", 
"National Security Agency/Central Security Service", 
"Navy Department", 
"Uniformed Services University of the Health Sciences", 
"Defense Nuclear Facilities Safety Board", 
"Education Department", 
"Energy Department", 
"Federal Energy Regulatory Commission", 
"National Nuclear Security Administration", 
"Southeastern Power Administration", 
"Southwestern Power Administration", 
"Western Area Power Administration", 
"Environmental Protection Agency", 
"Equal Employment Opportunity Commission", 
"Executive Office of the President", 
"Federal Communications Commission", 
"Federal Deposit Insurance Corporation", 
"Federal Election Commission", 
"Federal Housing Finance Agency", 
"Federal Maritime Commission", 
"Federal Reserve System", 
"Federal Trade Commission", 
"General Services Administration", 
"Government Accountability Office", 
"Government Ethics Office", 
"Government Publishing Office", 
"Health and Human Services Department", 
"Centers for Disease Control and Prevention", 
"Centers for Medicare & Medicaid Services", 
"Food and Drug Administration", 
"Indian Health Service", 
"National Institutes of Health", 
"Public Health Service", 
"Homeland Security Department", 
"Federal Emergency Management Agency", 
"Transportation Security Administration", 
"U.S. Citizenship and Immigration Services", 
"U.S. Customs and Border Protection", 
"U.S. Immigration and Customs Enforcement", 
"Justice Department", 
"Federal Bureau of Investigation", 
"Drug Enforcement Administration", 
"National Aeronautics and Space Administration", 
"National Archives and Records Administration", 
"National Counterintelligence Center", 
"National Credit Union Administration", 
"National Economic Council", 
"National Security Council", 
"National Transportation Safety Board", 
"Nuclear Regulatory Commission", 
"Occupational Safety and Health Review Commission", 
"Office of National Drug Control Policy", 
"Peace Corps", 
"Pension Benefit Guaranty Corporation", 
"Personnel Management Office", 
"Postal Service", 
"Securities and Exchange Commission", 
"Selective Service System", 
"Small Business Administration", 
"Social Security Administration", 
"Special Counsel Office", 
"State Department", 
"Transportation Department", 
"Federal Aviation Administration", 
"Federal Highway Administration", 
"Federal Motor Carrier Safety Administration", 
"Federal Railroad Administration", 
"Federal Transit Administration", 
"Great Lakes St. Lawrence Seaway Development Corporation", 
"Maritime Administration", 
"National Highway Traffic Safety Administration", 
"Treasury Department", 
"Internal Revenue Service", 
"U.S. House of Representatives", 
"United States Agency for Global Media", 
"United States Institute of Peace", 
"Veterans Affairs Department", 
"Women's Business Enterprise Interagency Committee", 
"Amazon", 
"Berkshire Hathaway", 
"Broadcom", 
"Eli Lilly", 
"Tesla", 
"JPMorgan Chase", 
"UnitedHealth (UNH)", 
"Exxon Mobil", 
"Oracle (ORCL)", 
"Mastercard (MA)", 
"Procter & Gamble (PG)", 
"Costco (COST)", 
"Home Depot (HD)", 
"Johnson & Johnson (JNJ)", 
"AbbVie (ABBV)", 
"Coca-Cola (KO)", 
"Bank of America", 
"Netflix", 
"Merck", 
"AMD", 
"Salesforce", 
"Chevron", 
"T-Mobile US", 
"Pepsico", 
"Adobe", 
"McDonald", 
"Cisco", 
"General Electric", 
"Danaher", 
"American Express", 
"Texas Instruments", 
"Caterpillar", 
"QUALCOMM", 
"Verizon", 
"Philip Morris", 
"ServiceNow", 
"Walt Disney", 
"Nextera Energy", 
"Intuit", 
"Amgen", 
"Intuitive Surgical", 
"Applied Materials", 
"Comcast", 
"Pfizer", 
"S&P Global", 
"Raytheon Technologies", 
"Goldman Sachs", 
"AT&T", 
"Lowe's Companies", 
"Union Pacific Corporation", 
"Progressive", 
"Booking Holdings (Booking.com)", 
"BlackRock", 
"Stryker Corporation", 
"Honeywell", 
"Nike", 
"TJX Companies", 
"Boston Scientific", 
"KKR & Co.", 
"ConocoPhillips", 
"Elevance Health", 
"Vertex Pharmaceuticals", 
"Arista Networks", 
"Micron Technology", 
"Citigroup", 
"Charles Schwab", 
"Prologis", 
"Analog Devices", 
"United Parcel Service", 
"Regeneron Pharmaceuticals", 
"Deere & Company", 
"Blackstone Group", 
"Automatic Data Processing", 
"Starbucks", 
"Marsh & McLennan Companies", 
"Palo Alto Networks", 
"American Tower", 
"Lam Research", 
"Gilead Sciences", 
"Bristol-Myers Squibb", 
"Fiserv", 
"Mondelez", 
"Southern Company", 
"Cigna", 
"Sherwin-Williams", 
"Boeing", 
"Southern Copper", 
"Intercontinental Exchange", 
"Duke Energy", 
"Zoetis", 
"Altria Group", 
"Moody's", 
"Colgate-Palmolive", 
"Palantir", 
"Waste Management", 
"General Dynamics", 
"Cintas", 
"Parker-Hannifin", 
"Airbnb", 
"Constellation Energy", 
"Synopsys", 
"TransDigm", 
"CME Group", 
"Chipotle Mexican Grill", 
"Illinois Tool Works", 
"Amphenol", 
"Welltower", 
"CVS Health", 
"3M", 
"Cadence Design Systems", 
"Freeport-McMoRan", 
"PNC Financial Services", 
"Carrier", 
"Ecolab", 
"Apollo Global Management", 
"Target", 
"U.S. Bancorp", 
"CrowdStrike", 
"Becton Dickinson", 
"EOG Resources", 
"GE Vernova", 
"CSX Corporation", 
"Air Products and Chemicals", 
"O'Reilly Automotive", 
"FedEx", 
"Enterprise Products", 
"McKesson", 
"Simon Property Group", 
"Republic Services", 
"Public Storage", 
"Emerson", 
"D. R. Horton", 
"Aflac", 
"Newmont", 
"Marvell Technology Group", 
"Credit One Bank", 
"FIS Global", 
"New Jersey Institute of Technology", 
"Alkami Technology", 
"Aerotech, Inc.", 
"Interstate Moving Relocation Logistics", 
"Lincoln Land Community College", 
"Santa Clara Valley Transportation Authority", 
"Metropolitan Transportation Authority", 
"Wipro Limited", 
"Virginia Commonwealth University", 
"Juniper Networks", 
"Naval Nuclear Laboratory", 
"StubHub", 
"Rivian", 
"NewsBreak", 
"Boston Scientific Corporation", 
"National Security Agency", 
"MUFG Bank, Ltd.", 
"Netsmart Technologies", 
"Medtronic", 
"f5", 
"Intellibee", 
"Automobile Club of Southern California", 
"Western Union", 
"Southside Va Community College", 
"Temple University", 
"ADP", 
"Ibotta", 
"University of Rochester", 
"Accenture Federal Services", 
"D365 Microsoft Partnership", 
"Digital Federal Credit Union / DCU", 
"Cognizant Technology Solutions", 
"NTT DATA", 
"JPMorganChase", 
"Benchmark Education Company", 
"American Physical Society", 
"Cambridge Technology Enterprises (CTE)", 
"Credit Acceptance", 
"Texas A&M University - San Antonio", 
"Cloud 9 Infosystems", 
"Firstlight Federal Credit Union", 
"Lennar", 
"Iowa 80 Truckstop", 
"ASRC Federal Holding Company", 
"Austin Peay State University", 
"Deluxe", 
"ECS Federal, LLC", 
"Hanscom Federal Credit Union", 
"Peloton", 
"Belay Technologies", 
"Autodesk", 
"Florida State College at Jacksonville", 
"Teradyne", 
"CEDENT", 
"Risk Solutions", 
"State of Ohio Jobs", 
"New York City Department of Education", 
"DraftKings", 
"Ada County", 
"NCR", 
"Education Department, State", 
"University of Idaho", 
"Raymond James Financial, Inc.", 
"University of New Hampshire", 
"Granite Telecommunications", 
"University at Albany", 
"GM Financial", 
"Disney Entertainment & ESPN Technology", 
"Scotiabank", 
"Fluidra North America", 
"Expedia Group", 
"Disney", 
"Citi", 
"TulaCo", 
"Sirius XM", 
"Adswizz", 
"d3v Technology Solutions", 
"Costco Wholesale", 
"PEPCO", 
"Virginia Tech", 
"Orbis", 
"NAVEX Global", 
"UST Global", 
"KUBRA", 
"Federal Client", 
"Laiba Technologies", 
"York Space Systems", 
"Merrick Bank", 
"State of Minnesota", 
"Taylor Corporation", 
"UKG", 
"College of Lake County", 
"San Bernardino County", 
"ByteDance", 
"Blue Cross of Idaho", 
"St. Catherine University", 
"State of Washington Dept. of Corrections", 
"California University Of Science And Medicine", 
"Kern County Superintendent Of Schools", 
"State of Wisconsin", 
"State of Wyoming", 
"Capital Region BOCES", 
"University of Kentucky", 
"ECS Federal LLC", 
"Utah State University", 
"Department of General Services", 
"Knight Federal Solutions Inc", 
"OpenGov", 
"MIDCONTINENT INDEPENDENT SYSTEM", 
"Tetra Tech", 
"CareFirst BlueCross BlueShield", 
"HHAeXchange", 
"ICF", 
"Avenu Insights & Analytics", 
"Benecard Services Inc.", 
"QTC Management, Inc.", 
"TRICARE", 
"Federal Aviation Administration (FAA) contractors", 
"Department of Defense contractors", 
"Health and Human Services contractors", 
"General Dynamics Mission Systems, Inc", 
"Booz Allen", 
"ManTech", 
"Missoula County", 
"CACI", 
"Two Six Technologies", 
"Skagit County", 
"Innovative Defense Technologies (IDT)", 
"Peraton", 
"KBR", 
"Steampunk", 
"Federal Aviation Administration contractors", 
"The Villages", 
"Urban Packaging Corp.", 
"Apixio", 
"Advanced Micro Devices, Inc.", 
"Verra Mobility", 
"TRICARE Management Activity", 
"U.S. Department of Agriculture contractors", 
"Federal Emergency Management Agency contractors", 
"Department of Homeland Security contractors", 
"CoBank", 
"Federal Home Loan Bank of Dallas", 
"State of Washington Employment Security Department", 
"The State of Oklahoma", 
"BOARD OF GOVERNORS of the FEDERAL RESERVE SYSTEM", 
"University of Washington", 
"North Wind Group", 
"Guidehouse", 
"L3Harris Technologies", 
"U.S. Department of Homeland Security (through Guidehouse and others)", 
"MIT Lincoln Laboratory", 
"NASA (through MIT Lincoln Laboratory and NASA contractors)", 
"US Bureau of Reclamation", 
"Federal Signal", 
"State of Texas", 
"General Dynamics Land Systems US", 
"State of Washington Administrative Office of the Courts", 
"Washington State Patrol", 
"CDC Foundation", 
"National Institutes of Health (NIH)", 
"Pinellas County Government", 
"T-Rex Solutions", 
"State Farm", 
"FSS Government Solutions", 
"Wespath Benefits and Investments", 
"CGI Group, Inc.", 
"DASNY - Dormitory Authority of the State of New York", 
"The MITRE Corporation", 
"State of Missouri", 
"USAA", 
"County of Santa Barbara", 
"Mayo Clinic", 
"Shriners Children's", 
"Trinity Health", 
"Veterans United Home Loans", 
"Saint Louis University", 
"NASPO", 
"State of Montana", 
"MS Dept. of Revenue", 
"City and County of San Francisco", 
"US Consumer Financial Protection Bureau", 
"Federal Reserve Bank of Boston", 
"State University of New York at New Paltz", 
"Johns Hopkins Applied Physics Laboratory (APL)", 
"Tarrant Regional Water District", 
"DAS Federal, LLC", 
"Department of Defense (DoD)", 
"US Federal Reserve Bank of Boston", 
"North Carolina A&T State University", 
"GEICO", 
"State of Colorado Job Opportunities", 
"METROPOLITAN WASHINGTON COUNCIL OF GOVERNMENTS", 
"POLICE DEPARTMENT", 
"City of Davenport", 
"Department of City Planning", 
"TEXAS EDUCATION AGENCY", 
"Nationwide IT Services", 
"Northwestern Memorial Healthcare", 
"Geisinger", 
"iDirect GOVERNMENT", 
"Pacific Northwest National Laboratory", 
"Los Alamos National Laboratory", 
"US Peace Corps", 
"Raytheon Technologies Corporate Headquarters", 
"City of San Antonio", 
"City of Sacramento", 
"NYC Office Of The Mayor", 
"San Francisco Health Plan", 
"City of El Paso, TX", 
"State of Idaho", 
"State of Louisiana", 
"State of New Mexico", 
"U.S. DHS Headquarters", 
"San Bernardino Superior Court", 
"U.S. District Court - Southern District of Georgia", 
"Lawrence Livermore National Laboratory", 
"Texas Workforce Commission", 
"State of Georgia", 
"City of Miami, FL", 
"California Governor's Office of Emergency Services", 
"City of Houston, TX", 
"Massachusetts School Building Authority", 
"Department of Med Assistance Svcs", 
"United Nations Federal Credit Union", 
"North Carolina Dept of Health and Human Services", 
"Metropolitan Transportation Commission", 
"Sacramento County Office of Education", 
"State of Utah", 
"State of Washington Parks and Recreation Commission", 
"Louisiana Supreme Court", 
"Government Tactical Solutions", 
"Texas Regional Bank", 
"North Dakota Office of Attorney General", 
"Experian", 
"Regions", 
"State of Washington Dept. of Commerce", 
"DEPARTMENT OF CORRECTION", 
"Lower Colorado River Authority", 
"Volusia County, FL", 
"Railroad Commission of Texas", 
"Texas A&M University", 
"Idaho National Laboratory", 
"Office of the Chief Financial Officer (OCFO)", 
"First American Financial Corporation", 
"Research Foundation for SUNY", 
"City of South Fulton", 
"Indiana Public Retirement System", 
"State of Arizona", 
"U.S. Bank National Association", 
"St. Mary's County Public Schools", 
"National Grid", 
"State of Arkansas", 
"Pantex", 
"DEPARTMENT OF TRANSPORTATION", 
"State of Washington State Board for Community & Technical Colleges (SBCTC)", 
"State of Maryland", 
"US Office of the Chief Economist", 
"Vanderbilt University Medical Center", 
"State of Indiana", 
"Serco North America", 
"NCR Atleos", 
"Delta Dental", 
"East West Bank", 
"Delta Dental of Missouri", 
"Edward Jones", 
"Ahold Delhaize USA", 
"First National Bank of America", 
"Athenahealth", 
"VeriskFieldprint", 
"Earth Space Technology Services, LLC", 
"Tensley Consulting, Inc.", 
"CTIS, Inc.", 
"Broadridge", 
"H&R Block", 
"International Paper", 
"Kimley-Horn", 
"Anthology, Inc.", 
"Donnelley Financial Solutions", 
"Syneos Health Commercial Solutions", 
"Parexel", 
"Red Hat, Inc.", 
"Paychex", 
"RedSail Technologies", 
"ImageTrend", 
"Red Bull", 
"Leading Path Consulting", 
"The Rawlings Group", 
"Changeis", 
"MEDLOGIX, LLC", 
"A-TEK Inc.", 
"Hinshaw & Culbertson", 
"SageSure", 
"EnergyCAP", 
"Snapchat", 
"Facebook App", 
"YouTube", 
"Neuralink", 
"TD Bank", 
"Governor’s Office of Land Use and Climate Innovation", 
"US Agricultural Marketing Service", 
"FINRA", 
"COMPTROLLER OF PUBLIC ACCOUNTS", 
"DEPT OF HEALTH/MENTAL HYGIENE", 
"North Carolina Department of Information Technology", 
"Connect for Health Colorado", 
"The City University of New York (CUNY)", 
"Region 10 Education Service Center", 
"New York State Environmental Facilities Corporation", 
"New Jersey Courts", 
"Environmental Facilities Corporation", 
"Hennepin County", 
"City of Philadelphia", 
"DMV IT Service", 
"County of Monmouth", 
"DeKalb CUSD #428", 
"Michigan Court of Appeals", 
"Metropolitan Police Department", 
"Purdue University", 
"Jacksonville Sheriff's Office", 
"Keck Medical Center of USC", 
"Center for Internet Security, Inc.", 
"City of Mt. Pleasant", 
"Florida Department of Highway Safety and Motor Vehicles", 
"The Christian and Missionary Alliance", 
"Public Partnerships LLC", 
"Summit Technologies, Inc.", 
"Evolver Inc", 
"Douglas County, KS Government", 
"Ivy Tech Community College", 
"ADMIN FOR CHILDREN'S SVCS", 
"Jeffco Public Schools", 
"Harris County", 
"Stanford Health Care", 
"MIT", 
"Vanguard", 
"Stifel", 
"gWorks", 
"NYC IT Inc", 
"City of Tyler", 
"City National Bank", 
"PayPal", 
"Sigma Defense", 
"Banner Bank", 
"International SOS", 
"Toyota", 
"Varo Bank", 
"Worldpay", 
"Mobility USA", 
"Lenovo", 
"MongoDB", 
"Udacity", 
"TowneBank", 
"DISH", 
"Snowflake", 
"University of Utah", 
"AMETEK, Inc.", 
"Department of Health Care Access and Information", 
"NOKIA", 
"M&T Bank", 
"Intone Networks", 
"Zendesk", 
"Flagstar Bank", 
"City of Austin", 
"TransUnion", 
"University of Michigan", 
"Robert Half", 
"SS&C", 
"Conduent State & Local Solutions, Inc", 
"Fulton Bank", 
"Fifth Third Bank", 
"City of Chicago", 
"Lowe's", 
"DHL", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"DTS America", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Qode", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Priority Technology Holdings, LLC", 
"St Jardins", 
"Aescape", 
"Radiant Digital", 
"Cornell Pump Company LLC", 
"GD Resources", 
"Domino's Corporate", 
"ABC COMPANIES", 
"Skilled Workforce", 
"NxtWave Disruptive Technologies Private Limited", 
"Re:Build Manufacturing", 
"TradeStation", 
"Gov Services Hub", 
"Mercor: OpenAI", 
"R.E. Michel Company, LLC", 
"Fincons.US, Inc.", 
"SimpliSafe", 
"Realtor.com Careers", 
"CFO Advisors", 
"Thalo Labs", 
"Aspira Connect", 
"C&A Associates", 
"JumpCloud", 
"Mitsubishi Electric US, Inc.", 
"Captions", 
"Hawthorn Bank", 
"Nestlé IT", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Priority Technology Holdings, LLC", 
"St Jardins", 
"Aescape", 
"Radiant Digital", 
"Cornell Pump Company LLC", 
"GD Resources", 
"Domino's Corporate", 
"ABC COMPANIES", 
"Skilled Workforce", 
"NxtWave Disruptive Technologies Private Limited", 
"Re:Build Manufacturing", 
"TradeStation", 
"Gov Services Hub", 
"Mercor: OpenAI", 
"R.E. Michel Company, LLC", 
"Fincons.US, Inc.", 
"SimpliSafe", 
"Realtor.com Careers", 
"CFO Advisors", 
"Thalo Labs", 
"Aspira Connect", 
"C&A Associates", 
"JumpCloud", 
"Mitsubishi Electric US, Inc.", 
"InvestCloud", 
"MoEngage Inc", 
"ResQ", 
"NICE", 
"Lucid Motors", 
"Emovis", 
"Tekcogno", 
"National Testing Network", 
"Modernizing Medicine, Inc.", 
"NICE", 
"Global Payment Holding Company", 
"Eco Material Technologies Inc", 
"Drone Powered Solutions", 
"Interactive Brokers", 
"Emovis US", 
"Lucid Motors", 
"Powersolv", 
"TP-Link Systems Inc.", 
"TwelveLabs", 
"Holman", 
"Cvent", 
"Design Interactive", 
"CaringBridge", 
"FanDuel", 
"Asphalt Buyer II LLC", 
"MetroStar", 
"Parker Group Inc", 
"TwelveLabs", 
"Parker Group Inc", 
"Rhombus", 
"PHOTRONICS INC", 
"Bandwidth", 
"Acuity Inc.", 
"Travis County", 
"LaunchDarkly", 
"Zayo Careers", 
"G2i Inc.", 
"Kipsu", 
"CEF Solutions Inc.", 
"absiusa", 
"IvoryCloud", 
"Tekcogno", 
"TeleWorld Solutions Inc", 
"School Employees Retirement System of Ohio", 
"TwelveLabs", 
"ADB Safegate", 
"Hexagon Safety & Infrastructure", 
"PHOTRONICS INC", 
"Cvent", 
"Nationwide", 
"TP-Link Systems Inc.", 
"AppFolio", 
"i3 Verticals", 
"UPMC", 
"HTX Labs", 
"BTI Solutions, Inc.", 
"Parker Group Inc", 
"Asphalt Buyer II LLC", 
"Keysight Technologies", 
"Same", 
"Dun & Bradstreet", 
"Ford Motor Company", 
"Department of Taxation", 
"ERPA", 
"MetroStar", 
"Signify", 
"Dataquad Inc", 
"Photon", 
"Kipsu", 
"CEF Solutions Inc.", 
"absiusa", 
"Tech-assist", 
"IvoryCloud", 
"Tekcogno", 
"TeleWorld Solutions Inc", 
"School Employees Retirement System of Ohio", 
"TwelveLabs", 
"ADB Safegate", 
"PHOTRONICS INC", 
"Cvent", 
"Nationwide", 
"TP-Link Systems Inc.", 
"AppFolio", 
"i3 Verticals", 
"UPMC", 
"HTX Labs", 
"BTI Solutions, Inc.", 
"Woongjin, Inc", 
"Parker Group Inc", 
"Asphalt Buyer II LLC", 
"Tangle Systems", 
"Keysight Technologies", 
"Same", 
"Dun & Bradstreet", 
"Ford Motor Company", 
"Department of Taxation", 
"ERPA", 
"MetroStar", 
"Signify", 
"Photon", 
"Clark County Credit Union", 
"Velocity Global", 
"Globus family of brands", 
"Cross Catholic Outreach", 
"Striversnet IT Services Pvt Ltd", 
"Radiant Digital", 
"DTS America", 
"CuraLinc Healthcare", 
"IT Engagements,Inc.", 
"Aven", 
"Noise Labs", 
"Velocity Global", 
"Special Order Systems Inc", 
"GD Resources LLC", 
"Hallmark Health Care Solutions, Inc", 
"DTS America", 
"Priority Technology Holdings, LLC", 
"St Jardins", 
"InfStones", 
"Aescape", 
"Radiant Digital", 
"Cornell Pump Company LLC", 
"GD Resources", 
"Domino's Corporate", 
"ABC COMPANIES", 
"Skilled Workforce", 
"NxtWave Disruptive Technologies Private Limited", 
"Re:Build Manufacturing", 
"TradeStation", 
"Gov Services Hub", 
"Mercor: OpenAI", 
"R.E. Michel Company, LLC", 
"Fincons.US, Inc.", 
"SimpliSafe", 
"Realtor.com Careers", 
"CFO Advisors", 
"Thalo Labs", 
"Aspira Connect", 
"C&A Associates", 
"JumpCloud", 
"Mitsubishi Electric US, Inc.", 
"InvestCloud", 
"MoEngage Inc", 
"ResQ", 
"NICE", 
"Lucid Motors", 
"Emovis", 
"Tekcogno", 
"National Testing Network", 
"Modernizing Medicine, Inc.", 
"NICE", 
"Global Payment Holding Company", 
"Eco Material Technologies Inc", 
"Interactive Brokers", 
"Emovis US", 
"Lucid Motors", 
"Powersolv", 
"TP-Link Systems Inc.", 
"TwelveLabs", 
"Holman", 
"Cvent", 
"Design Interactive", 
"CaringBridge", 
"FanDuel", 
"Asphalt Buyer II LLC", 
"MetroStar", 
"Parker Group Inc", 
"TwelveLabs", 
"Parker Group Inc", 
"Rhombus", 
"PHOTRONICS INC", 
"Bandwidth", 
"AmeriLux International", 
"Auxiant", 
"Quora", 
"First Community Credit Union", 
"E Source", 
"NBCUniversal", 
"Excellent Opportunity", 
"ServiceTitan, Inc.", 
"Asure Software", 
"Tempo Software Inc.", 
"Cheil Dallas", 
"HR Elements", 
"Royal Markets Inc.", 
"IDT", 
"VetsEZ", 
"Sparibis", 
"Asure Software", 
"Innodata Inc", 
"Honda", 
"GATEKEEPER SYSTEMS", 
"ABB", 
"Liberty Mutual", 
"Calendly", 
"Flatfile", 
"Simplot", 
"Piper Companies", 
"Karat", 
"Johnson & Johnson", 
"Publix", 
"Piper Companies", 
"Annapurna Labs (U.S.) Inc.", 
"General Motors", 
"American Sugar Refining", 
"Argano", 
"The Travelers Companies, Inc.", 
"Honda Research Institute USA", 
"EvenUp", 
"Information Technology Senior Management Forum", 
"Piper Companies", 
"CooperSurgical", 
"COPE Health Solutions", 
"Progyny, Inc", 
"Briljent", 
"Texas Health and Human Services Commission", 
"Lambda", 
"Information Technology Senior Management Forum", 
"Air Methods", 
"UCF", 
"American Sugar Refining", 
"SALT LAKE CITY CORP", 
"Bureau Veritas", 
"Labcorp", 
"Photon", 
"Optum", 
"DSFederal, Inc.", 
"DigitalOcean", 
"NRG Energy, Inc", 
"ATHES", 
"Unify", 
"Anblicks", 
"JCB North America", 
"The First National Bank & Trust Co", 
"Simon & Schuster", 
"Muckleshoot Casino Resort", 
"Intratek Computer, Inc.", 
"Hyundai Autoever America", 
"Handshake", 
"Best High Technologies PVT LTD", 
"Radix", 
"Publicis Groupe", 
"T-Mobile USA, Inc.", 
"Nestlé Purina", 
"Disney Entertainment and ESPN Product & Technology", 
"Tulane University", 
"SAP", 
"CNO Financial Group", 
"SSA Marine, Inc", 
"Rockwell Automation", 
"University of Alabama, Birmingham", 
"Fujifilm", 
"Republic National Distributing Company", 
"BlackRock Investments", 
"Philips", 
"Nestlé Purina", 
"Grindr", 
"Mozilla", 
"PGIM", 
"Elsevier", 
"Hofstra University", 
"Tulane University", 
"Illinois Institute of Technology", 
"Hewlett Packard Enterprise", 
"Frederick National Laboratory", 
"OpenAI", 
"NICE Systems", 
"Solventum", 
"Lumen", 
"Inter-American Development Bank", 
"Fidelity National Information Services", 
"Nestlé USA", 
"Prince Willam Water", 
"Southeast Alaska Regional Health Consortium", 
"Logix Federal Credit Union", 
"Popular Bank", 
"Indiana University", 
"E-Business International",
"E-Business International Inc",
"Amazon.com", 
"Handshake", 
"Red Robin International, Inc.", 
"Archer", 
"tvScientific", 
"Handshake", 
"SOUTH COLLEGE", 
"University of Maryland Medical System", 
"D. Kent Consulting Group, LLC", 
"New Mexico State University Foundation Inc", 
"Apria Healthcare LLC", 
"evlos", 
"Nextdoor", 
"Ema", 
"LendingClub Bank, N.A.", 
"World Wide Technology Holding, LLC", 
"E-Solutionts", 
"Point Broadband", 
"U.S. LawShield", 
"Chamberlain University", 
"Adtalem Global Education", 
"SwitchThink Solutions LLC", 
"Rectorseal", 
"Oran Inc", 
"Protect Life Michigan", 
"RevenueCat", 
"GovTact", 
"Power3 Solutions and Partnering Companies", 
"Ascension Federal Services Inc.", 
"Veterans Sourcing Group", 
"LendingPoint, LLC", 
"Samsung Research America", 
"Pattison ID", 
"NFI Industries", 
"American Nurses Association ANA", 
"XPRESSDOCS PARTNERS, LTD.", 
"Themis Insight", 
"Snapsheet", 
"Southminster Inc", 
"Outpower Energy Corp.", 
"Anduril Industries", 
"NFI Industries", 
"Thetford LLC & Norcold LLC", 
"Oil-Dri Corporation of America", 
"CSAT Solutions", 
"Cilable", 
"Govini", 
"Stand Together", 
"Kaizen Dynamics", 
"GenTech Associates", 
"Resource Management Associates, LLC", 
"Datalab USA", 
"Hudson Manpower", 
"Cross River", 
"MSX International", 
"Cross River", 
"Baker Tilly Advisory Group, LP", 
"STAT9 Technologies", 
"Resource Management Associates, LLC", 
"American Technology Experts Inc", 
"MIT Federal Credit Union", 
"Asurion", 
"Park Community Credit Union", 
"INFRANERGY", 
"Vetrics Group", 
"Tulsa Public Schools", 
"Beacon Credit Union - Indiana", 
"Ascella Technologies, Inc.", 
"MVK TECH", 
"Infoorigin Inc", 
"App Maisters Inc", 
"MVK TECH", 
"Indiana Legal Services, Inc.", 
"BankUnited", 
"The George Washington University Hospital", 
"Success Academy Charter Schools", 
"Hogue, Inc.", 
"ElevenLabs", 
"LOANBUD INC", 
"ELEVI Associates", 
"IMG Academy", 
"Aaditus Technologies LLC", 
"BitGo", 
"TMP Worldwide India Private Limited for ERS US", 
"Tamayo Federal Solutions LLC", 
"Delta Star Inc.", 
"Silco Fire & Security", 
"enGenius Consulting Group",
"Northern Tool & Equipment Company, Inc.",
"HERITAGE BANK INC",
"Northern Base Technologies",
"Healthy MD",
"Fiduciary Tech",
"Provectus",
"Oligo Space",
"CyberTrend Engineering LLC",
"San Francisco Federal Credit Union",
"TruGreen Limited Partnership",

]